version: '3'
services:
  backoffice:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - 5173:5173
    environment:
      SOME_VAR: ${ENV_VAL}

    restart: unless-stopped
