import { Type } from '@sinclair/typebox';
import { TDocument } from '../types';

export const getUniversalDocuments = (): TDocument[] => {
  const OptionalTypeAlphanumericString = Type.Optional(Type.String({ pattern: '^[a-zA-Z0-9]*$' }));
  const OptionalTypePastDate = Type.Optional(
    Type.String({
      format: 'date',
      formatMaximum: new Date().toISOString().split('T')[0],
    }),
  );

  return [
    {
      category: 'proof_of_registration',
      type: 'certificate_of_incorporation',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        registrationNumber: OptionalTypeAlphanumericString,
        issueDate: OptionalTypePastDate,
      }),
    },
    {
      category: 'proof_of_registration',
      type: 'business_registration_certificate',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        registrationNumber: OptionalTypeAlphanumericString,
        issueDate: OptionalTypePastDate,
        issuingAuthority: Type.Optional(Type.String()),
        businessAddress: Type.Optional(Type.String()),
        businessType: Type.Optional(Type.String()),
        expirationDate: Type.Optional(Type.String({ format: 'date' })),
      }),
    },
    {
      category: 'financial_information',
      type: 'corporate_tax_certificate',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        taxIdNumber: Type.Optional(Type.String()),
        issueDate: OptionalTypePastDate,
      }),
    },

    {
      category: 'collection_documents',
      type: 'afs_example',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        dbaName: Type.Optional(Type.String()),
        dbaAddress: Type.Optional(Type.String()),
        dbaCity: Type.Optional(Type.String()),
        dbaState: Type.Optional(Type.String()),
        dbaZip: Type.Optional(Type.String()),
        legalAddress: Type.Optional(Type.String()),
        legalCity: Type.Optional(Type.String()),
        legalState: Type.Optional(Type.String()),
        legalZip: Type.Optional(Type.String()),
        contactName: Type.Optional(Type.String()),
        contactTitle: Type.Optional(Type.String()),
        organizationType: Type.Optional(Type.String()),
        acceptsCards: Type.Optional(Type.Boolean()),
        annualCardVolume: Type.Optional(Type.String()),
        averageTicket: Type.Optional(Type.String()),
        highTicket: Type.Optional(Type.String()),
        industry: Type.Optional(Type.String()),
        mcc: Type.Optional(Type.String()),
        websiteUrl: Type.Optional(Type.String()),
        businessPhone: Type.Optional(Type.String()),
        businessEmail: Type.Optional(Type.String()),
        customerServicePhone: Type.Optional(Type.String()),
        businessStartDate: OptionalTypePastDate,
        percentCardPresent: Type.Optional(Type.Number()),
        salesToBusiness: Type.Optional(Type.Number()),
        salesToConsumer: Type.Optional(Type.Number()),
        bankName: Type.Optional(Type.String()),
        accountHolderName: Type.Optional(Type.String()),
        routingNumber: Type.Optional(Type.String()),
        accountNumber: Type.Optional(Type.String()),
        principalName: Type.Optional(Type.String()),
        principalTitle: Type.Optional(Type.String()),
        principalOwnershipPercentage: Type.Optional(Type.Number()),
        principalAddress: Type.Optional(Type.String()),
        principalPhone: Type.Optional(Type.String()),
        principalEmail: Type.Optional(Type.String()),
        principalSsn: Type.Optional(Type.String()),
        principalDob: OptionalTypePastDate,
        principalIdNumber: Type.Optional(Type.String()),
        principalIdState: Type.Optional(Type.String()),
        principalIdExpiration: Type.Optional(Type.String({ format: 'date' })),
        signatureDate: OptionalTypePastDate,
      }),
    },
    {
      category: 'proof_of_bank_ownership',
      type: 'bank_letter',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        accountHolderName: Type.Optional(Type.String()),
        accountNumber: Type.Optional(Type.String()),
        bankName: Type.Optional(Type.String()),
        issueDate: OptionalTypePastDate,
        branchInformation: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_bank_ownership',
      type: 'voided_check',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        accountHolderName: Type.Optional(Type.String()),
        accountNumber: Type.Optional(Type.String()),
        routingNumber: Type.Optional(Type.String()),
        bankName: Type.Optional(Type.String()),
        checkDate: OptionalTypePastDate,
      }),
    },
    {
      category: 'financial_information',
      type: 'bank_statement',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        accountHolderName: Type.Optional(Type.String()),
        accountNumber: Type.Optional(Type.String()),
        bankName: Type.Optional(Type.String()),
        statementPeriod: Type.Optional(Type.String()),
        issueDate: OptionalTypePastDate,
        physicalAddress: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_good_standing',
      type: 'certificate_of_good_standing',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        issueDate: OptionalTypePastDate,
      }),
    },
    {
      category: 'proof_of_ownership',
      type: 'certificate_of_directors_and_shareholders',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        directors: Type.Optional(Type.String()),
        shareholders: Type.Optional(Type.String()),
        issueDate: OptionalTypePastDate,
      }),
    },
    {
      category: 'proof_of_ownership',
      type: 'business_utility_bill',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        address: Type.Optional(Type.String()),
        utilityProvider: Type.Optional(Type.String()),
        billingPeriod: Type.Optional(Type.String()),
        amountDue: Type.Optional(Type.Number()),
        dueDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_ownership',
      type: 'company_address_document',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        registrationNumber: Type.Optional(Type.String()),
        address: Type.Optional(Type.String()),
        country: Type.Optional(Type.String()),
        city: Type.Optional(Type.String()),
        state: Type.Optional(Type.String()),
        postalCode: Type.Optional(Type.String()),
        street: Type.Optional(Type.String()),
        streetNumber: Type.Optional(Type.Number()),
        documentNumber: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        validUntil: Type.Optional(Type.String({ format: 'date' })),
      }),
    },
    {
      category: 'proof_of_ownership',
      type: 'website_compliance_document',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        websiteUrl: Type.Optional(Type.String()),
        complianceStandard: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'financial_documents',
      type: 'audited_financials_or_business_plan',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        registrationNumber: Type.Optional(Type.String()),
        fiscalYear: Type.Optional(Type.String()),
        reportPeriodStart: Type.Optional(Type.String({ format: 'date' })),
        reportPeriodEnd: Type.Optional(Type.String({ format: 'date' })),
        auditorName: Type.Optional(Type.String()),
        auditorFirm: Type.Optional(Type.String()),
        balanceSheet: Type.Optional(Type.String()),
        incomeStatement: Type.Optional(Type.String()),
        cashFlowStatement: Type.Optional(Type.String()),
        businessPlanSummary: Type.Optional(Type.String()),
        documentNumber: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
      }),
    },
    {
      category: 'corporate_authorization_and_delegation_documents',
      type: 'company_signature_authorization_letter',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        authorizedPerson: Type.Optional(Type.String()),
        position: Type.Optional(Type.String()),
        authorizationScope: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'corporate_governance_and_legal_fillings',
      type: 'corporate_documents_ssd',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        registrationNumber: Type.Optional(Type.String()),
        documentTitle: Type.Optional(Type.String()),
        filingDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'regulatory_compliance_certification',
      type: 'pci_certificate',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        certificateNumber: Type.Optional(Type.String()),
        certificationBody: Type.Optional(Type.String()),
        validFrom: Type.Optional(Type.String({ format: 'date' })),
        validUntil: Type.Optional(Type.String({ format: 'date' })),
        complianceLevel: Type.Optional(Type.String()),
      }),
    },

    {
      category: 'proof_of_identity',
      type: 'company_seal',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_domain_ownership',
      type: 'domain_purchase_record',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        domainName: Type.Optional(Type.String()),
        ownerName: Type.Optional(Type.String()),
        purchaseDate: OptionalTypePastDate,
        expiryDate: Type.Optional(Type.String({ format: 'date' })),
      }),
    },
    {
      category: 'financial_information',
      type: 'transaction_data_last_3_6_months',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        from: Type.Optional(Type.String({ format: 'date' })),
        to: Type.Optional(Type.String({ format: 'date' })),
        totalTransactions: Type.Optional(Type.Number()),
      }),
    },
    {
      category: 'financial_information',
      type: 'transaction_data_last_12_months',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        from: Type.Optional(Type.String({ format: 'date' })),
        to: Type.Optional(Type.String({ format: 'date' })),
        totalTransactions: Type.Optional(Type.Number()),
      }),
    },
    {
      category: 'proof_of_location',
      type: 'front_door_photo',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_location',
      type: 'interior_office_photo',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_business_compliance',
      type: 'permitted_sales_license',
      issuer: { country: 'UG' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        websiteUrl: Type.Optional(Type.String()),
        licenseNumber: OptionalTypeAlphanumericString,
        issueDate: OptionalTypePastDate,
        expiryDate: Type.Optional(Type.String({ format: 'date' })),
        permittedProductsOrServices: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_identity',
      type: 'passport',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        documentNumber: Type.Optional(Type.String()),
        firstName: Type.Optional(Type.String()),
        lastName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_identity',
      type: 'national_id',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        documentNumber: Type.Optional(Type.String()),
        firstName: Type.Optional(Type.String()),
        lastName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_identity',
      type: 'driver_licence',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        documentNumber: Type.Optional(Type.String()),
        firstName: Type.Optional(Type.String()),
        lastName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_identity',
      type: 'resident_card',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        documentNumber: Type.Optional(Type.String()),
        firstName: Type.Optional(Type.String()),
        lastName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_identity_ownership',
      type: 'selfie',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        documentNumber: Type.Optional(Type.String()),
        firstName: Type.Optional(Type.String()),
        lastName: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_bank_account_ownership',
      type: 'general_document',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        bankName: Type.Optional(Type.String()),
        accountNumber: Type.Optional(Type.String()),
        iban: Type.Optional(Type.String()),
        swiftCode: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'proof_of_address',
      type: 'general_document',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        address: Type.Optional(Type.String()),
        name: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        issuer: Type.Optional(Type.String()),
        accountNumber: Type.Optional(Type.String()),
        validUntil: Type.Optional(Type.String({ format: 'date' })),
        physicalAddress: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'pci-certification',
      type: 'general-document',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({}),
    },
    {
      category: 'general_documents',
      type: 'supplementary_document',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        documentTitle: Type.Optional(Type.String()),
        description: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'general_documents',
      type: 'letter_of_authorisation',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        authorizedPerson: Type.Optional(Type.String()),
        position: Type.Optional(Type.String()),
        authorizationScope: Type.Optional(Type.String()),
        issueDate: Type.Optional(Type.String({ format: 'date' })),
        documentNumber: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'company_structure',
      type: 'ownership_structure',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        companyName: Type.Optional(Type.String()),
        ownershipStructure: Type.Optional(Type.String()),
        parentCompanyName: Type.Optional(Type.String()),
        documentDate: Type.Optional(Type.String({ format: 'date' })),
      }),
    },
    {
      category: 'corporate_structure',
      type: 'operating_agreement',
      issuer: { country: 'ZZ' },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object({
        businessName: Type.Optional(Type.String()),
        documentDate: Type.Optional(Type.String({ format: 'date' })),
        ownershipStructure: Type.Optional(Type.String()),
        shareholderInformation: Type.Optional(Type.String()),
        beneficialOwners: Type.Optional(Type.String()),
        ownershipPercentages: Type.Optional(Type.String()),
        managingMembers: Type.Optional(Type.String()),
        votingRights: Type.Optional(Type.String()),
        corporateHierarchy: Type.Optional(Type.String()),
      }),
    },
    {
      category: 'business_document',
      type: 'firearms_dealer_authorization',
      issuer: {
        country: 'ZZ',
      },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object(
        {
          authorizationNumber: Type.String(),
          businessName: Type.String(),
          issuingAuthority: Type.String(),
          issueDate: Type.String({ format: 'date' }),
          expirationDate: Type.String({ format: 'date' }),
        },
        {
          required: [
            'authorizationNumber',
            'businessName',
            'issuingAuthority',
            'issueDate',
            'expirationDate',
          ],
        },
      ),
    },
    {
      category: 'business_document',
      type: 'cannabis_activity_license',
      issuer: {
        country: 'ZZ',
      },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object(
        {
          licenseNumber: Type.String(),
          businessName: Type.String(),
          activityType: Type.String(),
          issuingAuthority: Type.String(),
          issueDate: Type.String({ format: 'date' }),
          expirationDate: Type.String({ format: 'date' }),
        },
        {
          required: [
            'licenseNumber',
            'businessName',
            'activityType',
            'issuingAuthority',
            'issueDate',
            'expirationDate',
          ],
        },
      ),
    },
    {
      category: 'business_document',
      type: 'gambling_operator_license',
      issuer: {
        type: 'government',
        country: 'EU',
      },
      issuingVersion: 1,
      version: 1,
      propertiesSchema: Type.Object(
        {
          licenseNumber: Type.String(),
          businessName: Type.String(),
          issuingAuthority: Type.String(),
          licenseType: Type.Enum({
            'Online Casino': 'Online Casino',
            'Sports Betting': 'Sports Betting',
            Poker: 'Poker',
            Lottery: 'Lottery',
            Bingo: 'Bingo',
            'Physical Casino': 'Physical Casino',
          }),
          jurisdiction: Type.String(),
          issueDate: Type.String({ format: 'date' }),
          expirationDate: Type.String({ format: 'date' }),
        },
        {
          required: [
            'licenseNumber',
            'businessName',
            'issuingAuthority',
            'licenseType',
            'jurisdiction',
            'issueDate',
            'expirationDate',
          ],
        },
      ),
    },
  ];
};
