export const languages = [
  { const: 'aa', title: 'Afar' },
  { const: 'ab', title: 'Abkhazian' },
  { const: 'ae', title: 'Avestan' },
  { const: 'af', title: 'Afrikaans' },
  { const: 'ak', title: 'Akan' },
  { const: 'am', title: 'Amharic' },
  { const: 'an', title: 'Aragonese' },
  { const: 'ar', title: 'Arabic' },
  { const: 'as', title: 'Assamese' },
  { const: 'av', title: 'Avaric' },
  { const: 'ay', title: 'Aymara' },
  { const: 'az', title: 'Azerbaijani' },
  { const: 'ba', title: 'Bashkir' },
  { const: 'be', title: 'Belarusian' },
  { const: 'bg', title: 'Bulgarian' },
  { const: 'bh', title: 'Bihari languages' },
  { const: 'bi', title: 'Bislama' },
  { const: 'bm', title: 'Bambara' },
  { const: 'bn', title: 'Bengali' },
  { const: 'bo', title: 'Tibetan' },
  { const: 'br', title: 'Breton' },
  { const: 'bs', title: 'Bosnian' },
  { const: 'ca', title: 'Catalan; Valencian' },
  { const: 'ce', title: 'Chechen' },
  { const: 'ch', title: 'Chamorro' },
  { const: 'co', title: 'Corsican' },
  { const: 'cr', title: 'Cree' },
  { const: 'cs', title: 'Czech' },
  {
    const: 'cu',
    title: 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
  },
  { const: 'cv', title: 'Chuvash' },
  { const: 'cy', title: 'Welsh' },
  { const: 'da', title: 'Danish' },
  { const: 'de', title: 'German' },
  { const: 'dv', title: 'Divehi; Dhivehi; Maldivian' },
  { const: 'dz', title: 'Dzongkha' },
  { const: 'ee', title: 'Ewe' },
  { const: 'el', title: 'Greek, Modern (1453-)' },
  { const: 'en', title: 'English' },
  { const: 'eo', title: 'Esperanto' },
  { const: 'es', title: 'Spanish; Castilian' },
  { const: 'et', title: 'Estonian' },
  { const: 'eu', title: 'Basque' },
  { const: 'fa', title: 'Persian' },
  { const: 'ff', title: 'Fulah' },
  { const: 'fi', title: 'Finnish' },
  { const: 'fj', title: 'Fijian' },
  { const: 'fo', title: 'Faroese' },
  { const: 'fr', title: 'French' },
  { const: 'fy', title: 'Western Frisian' },
  { const: 'ga', title: 'Irish' },
  { const: 'gd', title: 'Gaelic; Scottish Gaelic' },
  { const: 'gl', title: 'Galician' },
  { const: 'gn', title: 'Guarani' },
  { const: 'gu', title: 'Gujarati' },
  { const: 'gv', title: 'Manx' },
  { const: 'ha', title: 'Hausa' },
  { const: 'he', title: 'Hebrew' },
  { const: 'hi', title: 'Hindi' },
  { const: 'ho', title: 'Hiri Motu' },
  { const: 'hr', title: 'Croatian' },
  { const: 'ht', title: 'Haitian; Haitian Creole' },
  { const: 'hu', title: 'Hungarian' },
  { const: 'hy', title: 'Armenian' },
  { const: 'hz', title: 'Herero' },
  { const: 'ia', title: 'Interlingua (International Auxiliary Language Association)' },
  { const: 'id', title: 'Indonesian' },
  { const: 'ie', title: 'Interlingue; Occidental' },
  { const: 'ig', title: 'Igbo' },
  { const: 'ii', title: 'Sichuan Yi; Nuosu' },
  { const: 'ik', title: 'Inupiaq' },
  { const: 'io', title: 'Ido' },
  { const: 'is', title: 'Icelandic' },
  { const: 'it', title: 'Italian' },
  { const: 'iu', title: 'Inuktitut' },
  { const: 'ja', title: 'Japanese' },
  { const: 'jv', title: 'Javanese' },
  { const: 'ka', title: 'Georgian' },
  { const: 'kg', title: 'Kongo' },
  { const: 'ki', title: 'Kikuyu; Gikuyu' },
  { const: 'kj', title: 'Kuanyama; Kwanyama' },
  { const: 'kk', title: 'Kazakh' },
  { const: 'kl', title: 'Kalaallisut; Greenlandic' },
  { const: 'km', title: 'Central Khmer' },
  { const: 'kn', title: 'Kannada' },
  { const: 'ko', title: 'Korean' },
  { const: 'kr', title: 'Kanuri' },
  { const: 'ks', title: 'Kashmiri' },
  { const: 'ku', title: 'Kurdish' },
  { const: 'kv', title: 'Komi' },
  { const: 'kw', title: 'Cornish' },
  { const: 'ky', title: 'Kirghiz; Kyrgyz' },
  { const: 'la', title: 'Latin' },
  { const: 'lb', title: 'Luxembourgish; Letzeburgesch' },
  { const: 'lg', title: 'Ganda' },
  { const: 'li', title: 'Limburgan; Limburger; Limburgish' },
  { const: 'ln', title: 'Lingala' },
  { const: 'lo', title: 'Lao' },
  { const: 'lt', title: 'Lithuanian' },
  { const: 'lu', title: 'Luba-Katanga' },
  { const: 'lv', title: 'Latvian' },
  { const: 'mg', title: 'Malagasy' },
  { const: 'mh', title: 'Marshallese' },
  { const: 'mi', title: 'Maori' },
  { const: 'mk', title: 'Macedonian' },
  { const: 'ml', title: 'Malayalam' },
  { const: 'mn', title: 'Mongolian' },
  { const: 'mr', title: 'Marathi' },
  { const: 'ms', title: 'Malay' },
  { const: 'mt', title: 'Maltese' },
  { const: 'my', title: 'Burmese' },
  { const: 'na', title: 'Nauru' },
  { const: 'nb', title: 'Bokmål, Norwegian; Norwegian Bokmål' },
  { const: 'nd', title: 'Ndebele, North; North Ndebele' },
  { const: 'ne', title: 'Nepali' },
  { const: 'ng', title: 'Ndonga' },
  { const: 'nl', title: 'Dutch; Flemish' },
  { const: 'nn', title: 'Norwegian Nynorsk; Nynorsk, Norwegian' },
  { const: 'no', title: 'Norwegian' },
  { const: 'nr', title: 'Ndebele, South; South Ndebele' },
  { const: 'nv', title: 'Navajo; Navaho' },
  { const: 'ny', title: 'Chichewa; Chewa; Nyanja' },
  { const: 'oc', title: 'Occitan (post 1500)' },
  { const: 'oj', title: 'Ojibwa' },
  { const: 'om', title: 'Oromo' },
  { const: 'or', title: 'Oriya' },
  { const: 'os', title: 'Ossetian; Ossetic' },
  { const: 'pa', title: 'Panjabi; Punjabi' },
  { const: 'pi', title: 'Pali' },
  { const: 'pl', title: 'Polish' },
  { const: 'ps', title: 'Pushto; Pashto' },
  { const: 'pt', title: 'Portuguese' },
  { const: 'qu', title: 'Quechua' },
  { const: 'rm', title: 'Romansh' },
  { const: 'rn', title: 'Rundi' },
  { const: 'ro', title: 'Romanian; Moldavian; Moldovan' },
  { const: 'ru', title: 'Russian' },
  { const: 'rw', title: 'Kinyarwanda' },
  { const: 'sa', title: 'Sanskrit' },
  { const: 'sc', title: 'Sardinian' },
  { const: 'sd', title: 'Sindhi' },
  { const: 'se', title: 'Northern Sami' },
  { const: 'sg', title: 'Sango' },
  { const: 'si', title: 'Sinhala; Sinhalese' },
  { const: 'sk', title: 'Slovak' },
  { const: 'sl', title: 'Slovenian' },
  { const: 'sm', title: 'Samoan' },
  { const: 'sn', title: 'Shona' },
  { const: 'so', title: 'Somali' },
  { const: 'sq', title: 'Albanian' },
  { const: 'sr', title: 'Serbian' },
  { const: 'ss', title: 'Swati' },
  { const: 'st', title: 'Sotho, Southern' },
  { const: 'su', title: 'Sundanese' },
  { const: 'sv', title: 'Swedish' },
  { const: 'sw', title: 'Swahili' },
  { const: 'ta', title: 'Tamil' },
  { const: 'te', title: 'Telugu' },
  { const: 'tg', title: 'Tajik' },
  { const: 'th', title: 'Thai' },
  { const: 'ti', title: 'Tigrinya' },
  { const: 'tk', title: 'Turkmen' },
  { const: 'tl', title: 'Tagalog' },
  { const: 'tn', title: 'Tswana' },
  { const: 'to', title: 'Tonga (Tonga Islands)' },
  { const: 'tr', title: 'Turkish' },
  { const: 'ts', title: 'Tsonga' },
  { const: 'tt', title: 'Tatar' },
  { const: 'tw', title: 'Twi' },
  { const: 'ty', title: 'Tahitian' },
  { const: 'ug', title: 'Uighur; Uyghur' },
  { const: 'uk', title: 'Ukrainian' },
  { const: 'ur', title: 'Urdu' },
  { const: 'uz', title: 'Uzbek' },
  { const: 've', title: 'Venda' },
  { const: 'vi', title: 'Vietnamese' },
  { const: 'vo', title: 'Volapük' },
  { const: 'wa', title: 'Walloon' },
  { const: 'wo', title: 'Wolof' },
  { const: 'xh', title: 'Xhosa' },
  { const: 'yi', title: 'Yiddish' },
  { const: 'yo', title: 'Yoruba' },
  { const: 'za', title: 'Zhuang; Chuang' },
  { const: 'zh', title: 'Chinese' },
  { const: 'zu', title: 'Zulu' },
];
