import { AlertsListSchema } from '@/domains/alerts/fetchers';
import { z } from 'zod';

export const tableData: z.input<typeof AlertsListSchema> = [
  {
    createdAt: '2024-02-01',
    merchant: 'SuperMart',
    severity: 'High',
    alertDetails: 'Unauthorized transaction',
    amountOfTxs: '5',
    assignee: 'John Doe',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-01',
    merchant: 'SuperMart',
    severity: 'Critical',
    alertDetails: 'Unauthorized transaction',
    amountOfTxs: '5',
    assignee: 'Unassigned',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-02',
    merchant: 'ElectroTech',
    severity: 'Medium',
    alertDetails: 'Unusual purchase pattern',
    amountOfTxs: '8',
    assignee: 'Jane Smith',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-03',
    merchant: 'FashionEmporium',
    severity: 'Low',
    alertDetails: 'Possible duplicate transaction',
    amountOfTxs: '3',
    assignee: 'Unassigned',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-04',
    merchant: 'GadgetZone',
    severity: 'High',
    alertDetails: 'Card not present transaction',
    amountOfTxs: '12',
    assignee: 'Alice Brown',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-05',
    merchant: 'HomeSupplies',
    severity: 'Medium',
    alertDetails: 'Large transaction amount',
    amountOfTxs: '6',
    assignee: 'Charlie Davis',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-06',
    merchant: 'TechSuperstore',
    severity: 'Low',
    alertDetails: 'Potential fraud alert',
    amountOfTxs: '4',
    assignee: 'Eva White',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-07',
    merchant: 'GroceryHaven',
    severity: 'High',
    alertDetails: 'Multiple failed login attempts',
    amountOfTxs: '7',
    assignee: 'Frank Black',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-08',
    merchant: 'BookEmpire',
    severity: 'Medium',
    alertDetails: 'Unrecognized device used',
    amountOfTxs: '9',
    assignee: 'Grace Green',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-09',
    merchant: 'SportsGear',
    severity: 'Low',
    alertDetails: 'Account login from new location',
    amountOfTxs: '5',
    assignee: 'Henry Taylor',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-10',
    merchant: 'FurnitureWorld',
    severity: 'High',
    alertDetails: 'Large transaction at odd hours',
    amountOfTxs: '11',
    assignee: 'Ivy Clark',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-11',
    merchant: 'JewelryPalace',
    severity: 'Medium',
    alertDetails: 'Unusual spending pattern',
    amountOfTxs: '8',
    assignee: 'Jack Turner',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-12',
    merchant: 'PetParadise',
    severity: 'Low',
    alertDetails: 'Possible account compromise',
    amountOfTxs: '4',
    assignee: 'Kelly Miller',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-13',
    merchant: 'ToolDepot',
    severity: 'High',
    alertDetails: 'Repeated declined transactions',
    amountOfTxs: '10',
    assignee: 'Leo Martinez',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-14',
    merchant: 'MusicMansion',
    severity: 'Medium',
    alertDetails: 'Unrecognized charge on account',
    amountOfTxs: '7',
    assignee: 'Mia Hall',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-15',
    merchant: 'HealthHub',
    severity: 'Low',
    alertDetails: 'Small transaction from foreign location',
    amountOfTxs: '3',
    assignee: 'Noah Brown',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-16',
    merchant: 'AutoZone',
    severity: 'High',
    alertDetails: 'Card used in high-risk location',
    amountOfTxs: '12',
    assignee: 'Olivia White',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-17',
    merchant: 'HomeDecor',
    severity: 'Medium',
    alertDetails: 'Unusual frequency of transactions',
    amountOfTxs: '9',
    assignee: 'Paul Johnson',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-18',
    merchant: 'OutdoorAdventure',
    severity: 'Low',
    alertDetails: 'Possible subscription fraud',
    amountOfTxs: '6',
    assignee: 'Quinn Smith',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-19',
    merchant: 'TravelWonders',
    severity: 'High',
    alertDetails: 'Large transaction at travel destination',
    amountOfTxs: '15',
    assignee: 'Riley Davis',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-20',
    merchant: 'CafeDelight',
    severity: 'Medium',
    alertDetails: 'Unrecognized charge at restaurant',
    amountOfTxs: '8',
    assignee: 'Sam Turner',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-21',
    merchant: 'ArtGallery',
    severity: 'Low',
    alertDetails: 'Possible identity theft',
    amountOfTxs: '4',
    assignee: 'Tina Clark',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-22',
    merchant: 'FitnessFocus',
    severity: 'High',
    alertDetails: 'Large transaction at fitness center',
    amountOfTxs: '10',
    assignee: 'Ulysses Martin',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-23',
    merchant: 'TechGizmos',
    severity: 'Medium',
    alertDetails: 'Unrecognized online purchase',
    amountOfTxs: '7',
    assignee: 'Victoria Hall',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-24',
    merchant: 'BabyBliss',
    severity: 'Low',
    alertDetails: 'Unusual baby product purchase',
    amountOfTxs: '5',
    assignee: 'Walter Brown',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-25',
    merchant: 'GardenGroove',
    severity: 'High',
    alertDetails: 'Large transaction at garden supply store',
    amountOfTxs: '13',
    assignee: 'Xena White',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-26',
    merchant: 'FashionFiesta',
    severity: 'Medium',
    alertDetails: 'Unusual fashion-related purchase',
    amountOfTxs: '8',
    assignee: 'Yohan Johnson',
    status: 'Resolved',
  },
  {
    createdAt: '2024-02-27',
    merchant: 'OfficeEssentials',
    severity: 'Low',
    alertDetails: 'Small transaction from office supply store',
    amountOfTxs: '3',
    assignee: 'Zara Smith',
    status: 'Pending',
  },
  {
    createdAt: '2024-02-28',
    merchant: 'PetParadise',
    severity: 'High',
    alertDetails: 'Multiple transactions at pet store',
    amountOfTxs: '11',
    assignee: 'Aaron Davis',
    status: 'Resolved',
  },
];
