export const industries = [
  'Adult Entertainment and Products,',
  'Aerospace Engineering,',
  'Agriculture and Farming,',
  'Airlines and Aviation,',
  'Airlines and Charter Services,',
  'Alcohol Sales,',
  'Alternative Medicine,',
  'Animation,',
  'Antiques,',
  'Apparel and Fashion,',
  'Apparel and Fashion,',
  'Architectural Restoration,',
  'Architecture and Planning,',
  'Arts and Crafts Supplies,',
  'Arts and Crafts,',
  'Astrology and Spiritual,',
  'Auctions and Auctioneering,',
  'Auctions and Penny Auctions,',
  'Automotive Repair,',
  'Automotive,',
  'Aviation & Aerospace,',
  'Bail Bonds,',
  'Bakery and Confections,',
  'Banking and Finance,',
  'Beverage Production,',
  'Bicycle Sales and Service,',
  'Binary Options Trading,',
  'Biomedical,',
  'Biotechnology,',
  'Bitcoins and Cryptocurrencies,',
  'Boat Building and Repair,',
  'Breweries and Distilleries,',
  'Bridal Services,',
  'Broadcast Media,',
  'Building Materials,',
  'Candle and Aromatherapy,',
  'Cannabis and CBD Products,',
  'Cannabis,',
  'Ceramics and Pottery,',
  'Charities and Non-Profits,',
  'Chemicals,',
  'Childcare,',
  'Cigarettes, E-Cigarettes, and Vape Shops,',
  'Civic and Social Organizations,',
  'Civil Engineering,',
  'Clinical Research,',
  'Collectibles,',
  'Collection Agencies,',
  'Commercial Fishing,',
  'Commercial Real Estate,',
  'Commodities Trading,',
  'Computer & Network Security,',
  'Computer Gaming,',
  'Computer Hardware,',
  'Computer Software,',
  'Construction,',
  'Consumer Electronics,',
  'Consumer Goods,',
  'Consumer Services,',
  'Cosmetics and Beauty,',
  'Craft Brewing and Distilling,',
  'Credit Repair Services,',
  'Dairy,',
  'Dance and Dance Instruction,',
  'Data Analysis and Statistics,',
  'Dating Services,',
  'Debt Consolidation and Restructuring,',
  'Defense and Space,',
  'Design,',
  'Digital Downloads,',
  'Digital Media,',
  'Direct Marketing,',
  'E-commerce,',
  'Education and E-Learning,',
  'Elderly Care,',
  'Electrical and Electronic Manufacturing,',
  'Electrical Equipment,',
  'Emergency Services,',
  'Entertainment,',
  'Environmental Services,',
  'Equine and Equestrian,',
  'eSports and Betting,',
  'Event Ticket Brokers,',
  'Events Services,',
  'Executive Office and Management,',
  'Facilities Services,',
  'Farming and Agriculture Equipment,',
  'Fashion Accessories,',
  'Financial Services,',
  'Fine Art,',
  'Firearms, Ammunition, and Accessories,',
  'Fireworks Sales,',
  'Fishery,',
  'Florists,',
  'Food and Beverages,',
  'Food Production,',
  'Food Trucks,',
  'Footwear Manufacturing,',
  'Forestry and Logging,',
  'Forex Trading,',
  'Fossil Fuels,',
  'Funeral Services,',
  'Furniture Manufacturing,',
  'Furniture,',
  'Gambling and Casinos,',
  'Gambling and Casinos,',
  'Genomics and Genetics,',
  'Geology and Earth Sciences,',
  'Glass, Ceramics and Concrete,',
  'Government and Public Services,',
  'Graphic Design,',
  'Green and Sustainable Living,',
  'Health, Wellness and Fitness,',
  'Higher Education,',
  'Hobbies and Crafts,',
  'Home and Garden,',
  'Home Health Care,',
  'Homewares,',
  'Horoscopes and Psychic Services,',
  'Horticulture,',
  'Hospital and Healthcare,',
  'Hospitality,',
  'Human Resources,',
  'Illegal and Black Market Products,',
  'Import and Export,',
  'Indigenous Services,',
  'Industrial Automation,',
  'Infectious Diseases,',
  'Information Services,',
  'Information Technology,',
  'Insurance,',
  'Interior Design,',
  'International Affairs,',
  'International Trade and Development,',
  'Internet,',
  'Investment Banking,',
  'Jewelry Sales,',
  "Kid's Products,",
  'Language Schools and Instruction,',
  'Laundry and Dry Cleaning,',
  'Law and Legal Services,',
  'Leisure and Travel,',
  'Library and Archives,',
  'Lighting,',
  'Linguistics,',
  'Logistics and Supply Chain,',
  'Luxury and Specialty Goods,',
  'Luxury Goods and Jewelry,',
  'Machinery,',
  'Magazine Subscriptions,',
  'Magazines,',
  'Mail and Shipping Services,',
  'Marine Sciences,',
  'Maritime,',
  'Marketing and Advertising,',
  'Materials Research,',
  'Mechanical or Industrial Engineering,',
  'Media Production,',
  'Medical and Recreational Marijuana Dispensaries,',
  'Medical Devices,',
  'Medical Practice,',
  'Mental Health Care,',
  'Meteorology and Weather Services,',
  'Microelectronics,',
  'Military and Defense,',
  'Mining and Metals,',
  'Modeling and Talent Agencies,',
  'Motion Pictures and Film,',
  'Multi-Level Marketing (MLM),',
  'Museums and Institutions,',
  'Music,',
  'Nanotechnology,',
  'Natural and Organic Products,',
  'Neurosciences,',
  'Newspapers,',
  'Nuclear Energy,',
  'Nutraceuticals and Supplements,',
  'Nutrition and Dietetics,',
  'Office Supplies,',
  'Oil and Energy,',
  'Online Gaming and In-game Items,',
  'Online Media,',
  'Optometry,',
  'Outsourcing and Offshoring,',
  'Packaging,',
  'Paper and Forest Products,',
  'Pawn Shops,',
  'Payday Loans and Lenders,',
  'Performing Arts,',
  'Pet Products and Services,',
  'Pharmaceuticals and Drug Stores,',
  'Pharmaceuticals,',
  'Philanthropy,',
  'Photography,',
  'Plastics,',
  'Podcasting,',
  'Police and Security Services,',
  'Political Organization and Lobbying,',
  'Postal Services,',
  'Poultry,',
  'Precious Metals and Stones,',
  'Primary and Secondary Education,',
  'Printing,',
  'Private and Specialty Education,',
  'Professional Training and Coaching,',
  'Public Broadcasting,',
  'Public Policy,',
  'Public Relations and Communications,',
  'Publishing,',
  'Pulp and Paper,',
  'Railroad,',
  'Ranching,',
  'Real Estate,',
  'Religious Organizations,',
  'Renewable Energy,',
  'Research,',
  'Restaurants,',
  'Retail,',
  'Robotics,',
  'Satellites,',
  'Saunas and Spas,',
  'Security and Investigations,',
  'Semiconductors,',
  'Shipbuilding,',
  'Short-Term Rentals (e.g., Airbnb),',
  'Social Media,',
  'Space Exploration,',
  'Specialty Foods,',
  'Sports Coaching and Instruction,',
  'Sports Forecasting or Odds Making,',
  'Sports,',
  'Staffing and Recruiting,',
  'Supermarkets,',
  'Sustainable Agriculture,',
  'Taxidermy,',
  'Tea Production,',
  'Telecommunications,',
  'Telemarketing,',
  'Telemedicine,',
  'Television Broadcasting,',
  'Textiles,',
  'Therapeutics,',
  'Timeshares,',
  'Tobacco and Cigar Shops,',
  'Tobacco,',
  'Toys and Games,',
  'Trade and Development,',
  'Trade Shows and Events,',
  'Traditional Energy,',
  'Translation and Localization,',
  'Travel Agencies and Tour Operators,',
  'Urban Planning,',
  'Utilities,',
  'Veterinary Medicine,',
  'Veterinary,',
  'Video Production,',
  'Virtual Reality and Augmented Reality,',
  'Warehousing,',
  'Water Treatment,',
  'Weapons and Knives Sales,',
  'Wearable Technology,',
  'Weight Loss Programs and Products',
  'Wholesale,',
  'Wine and Spirits,',
  'Writing and Editing',
  'Yoga and Pilates,',
  'Zoology and Wildlife',
];
