import {
  AML_CHECK,
  BETWEEN,
  EQUALS,
  GT,
  GTE,
  IN,
  IN_CASE_INSENSITIVE,
  LAST_YEAR,
  LT,
  LTE,
  NOT_EQUALS,
  EXISTS,
  NOT_IN,
  FUZZY_MATCH_SCORE_LT,
  IDV_CHECK,
  COMPANY_SANCTIONS_CATEGORIES,
} from './index';

import { OPERATION } from './enums';

export { OPERATORS_WITHOUT_PATH_COMPARISON, OPERATORS_WITH_THRESHOLD } from './index';

export type { TUnifiedApiClient } from './index';

export const OperationHelpers = {
  [OPERATION.EQUALS]: EQUALS,
  [OPERATION.NOT_EQUALS]: NOT_EQUALS,
  [OPERATION.EXISTS]: EXISTS,
  [OPERATION.BETWEEN]: BETWEEN,
  [OPERATION.GT]: GT,
  [OPERATION.GTE]: GTE,
  [OPERATION.LT]: LT,
  [OPERATION.LTE]: LTE,
  [OPERATION.LAST_YEAR]: LAST_YEAR,
  [OPERATION.IN]: IN,
  [OPERATION.IN_CASE_INSENSITIVE]: IN_CASE_INSENSITIVE,
  [OPERATION.NOT_IN]: NOT_IN,
  [OPERATION.AML_CHECK]: AML_CHECK,
  [OPERATION.FUZZY_MATCH_SCORE_LT]: FUZZY_MATCH_SCORE_LT,
  [OPERATION.IDV_CHECK]: IDV_CHECK,
  [OPERATION.COMPANY_SANCTIONS_CATEGORIES]: COMPANY_SANCTIONS_CATEGORIES,
} as const;
