export const OPERATION = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS',
  BETWEEN: 'BETWEEN',
  GT: 'GT',
  LT: 'LT',
  GTE: 'GTE',
  LTE: 'LTE',
  LAST_YEAR: 'LAST_YEAR',
  EXISTS: 'EXISTS',
  IN: 'IN',
  NOT_IN: 'NOT_IN',
  AML_CHECK: 'AML_CHECK',
} as const;

export const OPERATIONS = [
  OPERATION.EQUALS,
  OPERATION.NOT_EQUALS,
  OPERATION.BETWEEN,
  OPERATION.GT,
  OPERATION.LT,
  OPERATION.GTE,
  OPERATION.LTE,
  OPERATION.LAST_YEAR,
  OPERATION.EXISTS,
  OPERATION.IN,
  OPERATION.NOT_IN,
  OPERATION.AML_CHECK,
];

export const OPERATOR = {
  AND: 'and',
  OR: 'or',
} as const;
