{
 "title": "BullMQ Dashboard",
 "tags": [ "bullmq" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Completed Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bullmq_jobs_completed_total", "legendFormat": "Completed Jobs" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bullmq_jobs_failed_total", "legendFormat": "Failed Jobs" }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bullmq_jobs_active", "legendFormat": "Active Jobs" }
   ]
  },
  {
   "title": "Waiting Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bullmq_jobs_waiting", "legendFormat": "Waiting Jobs" }
   ]
  },
  {
   "title": "Native BullMQ - Waiting Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bullmq_job_count{state=\"waiting\"}",
     "legendFormat": "{{queue}} - Waiting"
    }
   ]
  },
  {
   "title": "Native BullMQ - Active Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bullmq_job_count{state=\"active\"}",
     "legendFormat": "{{queue}} - Active"
    }
   ]
  },
  {
   "title": "Native BullMQ - Completed Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bullmq_job_count{state=\"completed\"}",
     "legendFormat": "{{queue}} - Completed"
    }
   ]
  },
  {
   "title": "Native BullMQ - Failed Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bullmq_job_count{state=\"failed\"}",
     "legendFormat": "{{queue}} - Failed"
    }
   ]
  }
 ]
}