{
 "title": "BullMQ Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BullMQ Waiting Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bullmq_job_count{state=\"waiting\"}",
     "legendFormat": "Waiting Jobs"
    }
   ]
  },
  {
   "title": "BullMQ Active Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bullmq_job_count{state=\"active\"}",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bullmq_job_count{state=\"completed\"})"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bullmq_job_count{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "All Queue States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "bullmq_job_count", "legendFormat": "{{state}}" }
   ]
  }
 ]
}