export const websiteMonitoringMock = {
  entity: {
    id: 'ID-1234',
    data: {
      country: 'IL',
      companyName: 'dogo',
      additionalInfo: { store: { website: { mainWebsite: 'https://dogo.co.il' } } },
    },
    type: 'business',
    ballerineEntityId: 'clooaciqo0001y8n07dyxe554',
  },
  documents: [],
  customerName: 'Customer 1',
  pluginsOutput: {
    website_monitoring: {
      data: {
        id: 19750073,
        ls_tags: [],
        ls_action: {
          reason:
            'LegitScript has verified that this merchant is engaged in transaction laundering and presents elevated risk for BRAM and VIRP violations. This merchant appears to be accepting card payments on behalf of buybuybabybigsale.com. At the time of analysis, buybuybabybigsale.com was directing users to the merchant URL to complete their payment.',
          actions: ['bram', 'tl_confirmed', 'gbpp'],
          published_at: '2023-11-02T22:38:42.000Z',
          content_labels: [{ id: 65, label: 'IP' }],
        },
        created_at: '2023-10-27T14:56:18.000Z',
        customer_tags: [],
        customer_action: { action: null, comment: null, created_at: null },
        merchant_details: {
          ica: null,
          iso: null,
          agent: null,
          custom: null,
          status: 'published',
          sub_iso: null,
          dba_city: null,
          dba_name: null,
          dba_phone: null,
          dba_state: null,
          dba_street: null,
          dba_country: null,
          merchant_id: 'RO-US-09-1',
          merchant_url: 'https://www.katherinestyles.com',
          referral_url: null,
          merchant_city: 'Colorado Springs',
          merchant_name: 'Petal Empire Trading Co.',
          acquiring_bank: null,
          merchant_email: 'pay@katherinestyles.com',
          merchant_phone: '(877) 438-5929',
          dba_postal_code: null,
          merchant_region: null,
          merchant_street: '10363 Sentry Post Place',
          merchant_country: 'US',
          business_owner_city: null,
          business_owner_name: 'Petal Empire Trading Co.',
          merchant_descriptor: null,
          business_owner_phone: '(877) 438-5929',
          business_owner_state: null,
          merchant_postal_code: '80925',
          business_owner_street: '10363 Sentry Post Place',
          business_owner_country: null,
          merchant_category_code: null,
          additional_merchant_urls: null,
          associated_email_addresses: null,
          business_owner_postal_code: null,
        },
        merchant_domains: [
          {
            merchant_url: 'https://www.katherinestyles.com',
            website_registrar: { name: null, risk_level: null, iana_number: null },
          },
        ],
        website_registrar: { name: null, risk_level: null, iana_number: null },
      },
      metadata: {
        type: 'website-monitoring',
        result: {
          message: 'Merchant application accepted.',
          correlation_id: 'c5b8492b-b30b-45cd-95fe-f237cb5dba0a',
        },
      },
      vendor: 'legitscript',
    },
  },
  workflowRuntimeId: 'clooacir30003y8n0ze9xjpwy',
};
