export const putPluginsExampleResponse = {
  apiPlugins: [
    {
      name: 'invitation-email',
      pluginKind: 'template-email',
      template: 'invitation',
      successAction: 'INVITATION_SENT',
      errorAction: 'INVITATION_FAILURE',
      stateNames: ['collection_invite'],
    },
    {
      name: 'businessInformation',
      vendor: 'asia-verify',
      pluginKind: 'registry-information',
      stateNames: ['get_vendor_data'],
      displayName: 'Registry Information',
      errorAction: 'VENDOR_FAILED',
      successAction: 'VENDOR_DONE',
    },
    {
      name: 'companySanctions',
      vendor: 'asia-verify',
      pluginKind: 'company-sanctions',
      stateNames: ['get_vendor_data'],
      displayName: 'Company Sanctions',
      errorAction: 'VENDOR_FAILED',
      successAction: 'VENDOR_DONE',
    },
    {
      name: 'ubo',
      vendor: 'asia-verify',
      pluginKind: 'ubo',
      stateNames: ['get_vendor_data'],
      displayName: 'UBO Check',
      errorAction: 'VENDOR_FAILED',
      successAction: 'VENDOR_DONE',
    },
    {
      name: 'resubmission-email',
      pluginKind: 'template-email',
      template: 'resubmission',
      stateNames: ['pending_resubmission'],
      errorAction: 'EMAIL_FAILURE',
      successAction: 'EMAIL_SENT',
    },
    {
      name: 'merchantMonitoring',
      pluginKind: 'merchant-monitoring',
      vendor: 'ballerine',
      stateNames: ['run_merchant_monitoring'],
      successAction: 'MERCHANT_MONITORING_SUCCESS',
      errorAction: 'MERCHANT_MONITORING_FAILED',
      reportType: 'MERCHANT_REPORT_T1',
      merchantMonitoringQualityControl: false,
      dataMapping: `
        customerId: metadata.customerId,
        merchantId: entity.ballerineEntityId,
        countryCode: entity.data.country,
        websiteUrl: entity.data.additionalInfo.store.website.mainWebsite,
      `,
    },
  ],
  commonPlugins: [
    {
      name: 'riskEvaluation',
      pluginKind: 'riskRules',
      stateNames: ['manual_review'],
      rulesSource: {
        source: 'notion',
        databaseId: 'aaaaaaaaaaaaaa',
      },
    },
  ],
  childWorkflowPlugins: [],
  dispatchEventPlugins: [],
};
