global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bullmq-metrics'
    static_configs:
      - targets: ['localhost:9464']
    metrics_path: /metrics

  - job_name: 'workflows-service'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: /api/metrics/prometheus
