version: '3'
services:
  ballerine-case-managment:
    image: ghcr.io/ballerine-io/backoffice:fintech_devcon
    ports:
      - 5137:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-kyb-app:
    image: ghcr.io/ballerine-io/kyb-app:fintech_devcon
    ports:
      - 5201:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
    environment:
      VITE_API_URL: 'http://localhost:3000/api/v1/'
      VITE_KYB_DEFINITION_ID: 'kyb_parent_kyc_session_example'
  ballerine-workflow-service:
    image: ghcr.io/ballerine-io/workflows-service:fintech_devcon
    command:
      - /bin/sh
      - -c
      - |
        npm run db:init
        npm run seed:ex
        dumb-init npm run prod
    ports:
      - 3000:3000
    environment:
      BCRYPT_SALT: 10
      JWT_SECRET_KEY: "secret"
      JWT_EXPIRATION: "10d"
      DB_URL: postgres://admin:admin@ballerine-postgres:5432
      API_KEY: "secret"
      NODE_ENV: "development"
      COMPOSE_PROJECT_NAME: "ballerine-x"
      DB_PORT: 5432
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      SESSION_SECRET: "secret"
      BACKOFFICE_CORS_ORIGIN: http://localhost:5137
      HEADLESS_EXAMPLE_CORS_ORIGIN: http://localhost:5173
      WORKFLOW_DASHBOARD_CORS_ORIGIN: http://localhost:5200
      PORT: 3000
      KYB_EXAMPLE_CORS_ORIGIN: http://localhost:5201
      IS_DEMO: "true"
      KYB_API_URL: 'https://unified-api-test.eu.ballerine.app'
      WEBHOOK_SECRET: webhook_secret
      KYC_API_URL: https://unified-api-test.eu.ballerine.app
      APP_API_URL: https://alon.ballerine.dev
      EMAIL_API_TOKEN: ''
      EMAIL_API_URL: https://api.sendgrid.com/v3/mail/send
      UNIFIED_API_TOKEN: ""
    depends_on:
      ballerine-postgres:
        condition: service_healthy
    restart: on-failure
  ballerine-workflows-dashboard:
    image: ghcr.io/ballerine-io/workflows-dashboard:fintech_devcon
    ports:
      - 5200:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-postgres:
    image: sibedge/postgres-plv8:15.3-3.1.7
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres15:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - admin
      timeout: 45s
      interval: 10s
      retries: 10
volumes:
  postgres15: ~
