version: '3'
services:
  backoffice:
    volumes:
      - ../apps/backoffice-v2/:/app
      - /app/node_modules
    build:
      context: ../apps/backoffice-v2/
      target: "dev"
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${BACKOFFICE_PORT}:${BACKOFFICE_PORT}
    depends_on:
      - service      
    restart: on-failure
  headlessservice:
    volumes:
      - ../examples/headless-example/:/app
      - /app/node_modules
    build:
      context: ../examples/headless-example
      target: "dev"
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${HEADLESS_SVC_PORT}:${HEADLESS_SVC_PORT}
    depends_on:
      - service
    restart: on-failure    
  workflows-dashboard:
    volumes:
      - ../apps/workflows-dashboard/:/app
      - /app/node_modules
    build:
      context: ../apps/workflows-dashboard
      target: "dev"
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${WORKFLOW_DASHBOARD_PORT}:${WORKFLOW_DASHBOARD_PORT}
    depends_on:
      - service
    restart: on-failure
  websocket-service:
    volumes:
      - ../services/websocket-service/:/app
      - /app/node_modules  
    build:
      context: ../services/websocket-service
      target: "dev"
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${WEBSOCKET_SVC_PORT}:${WEBSOCKET_SVC_PORT}
    depends_on:
      - service
    restart: on-failure    
  service:
    volumes:
      - ../services/workflows-service/:/app
      - /app/node_modules
    build:
      context: ../services/workflows-service/
      target: "dev"
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${WORKFLOW_SVC_PORT}:${WORKFLOW_SVC_PORT}
    environment:
      BCRYPT_SALT: ${BCRYPT_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}
      API_KEY: ${API_KEY}
      NODE_ENV: ${NODE_ENV}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      BACKOFFICE_CORS_ORIGIN: http://localhost:${BACKOFFICE_PORT}
      HEADLESS_EXAMPLE_CORS_ORIGIN: http://localhost:${HEADLESS_SVC_PORT}
      WORKFLOW_DASHBOARD_CORS_ORIGIN: http://localhost:${WORKFLOW_DASHBOARD_PORT}
      PORT: ${WORKFLOW_SVC_PORT}
    depends_on:
      - migrate
  migrate:
    volumes:
      - ../services/workflows-service/:/app
      - /app/node_modules
    build:
      context: ../services/workflows-service/
      target: "dev"
      args:
        NPM_LOG_LEVEL: notice
    command: npm run db:init
    working_dir: /app
    environment:
      BCRYPT_SALT: ${BCRYPT_SALT}
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: postgres:12
    ports:
      - 5430:${DB_PORT}
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      timeout: 45s
      interval: 10s
      retries: 10
