{{- if .Values.headlessexample.ingress.enabled -}}
{{- $fullName := .Values.headlessexample.nameOverride -}}
{{- $svcPort := .Values.headlessexample.service.port -}}
{{- $pathtype := .Values.headlessexample.ingress.pathtype -}}
{{- $ingressPath := .Values.headlessexample.ingress.path }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.headlessexample.nameOverride }}
{{- with .Values.headlessexample.ingress.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{ end }}
spec:
  {{- if .Values.headlessexample.ingress.className }}
  ingressClassName: {{ .Values.headlessexample.ingress.className | quote }}
  {{- end }}
{{- if .Values.headlessexample.ingress.tls }}
  tls:
  {{- if .ingressPath }}
  {{- range .Values.headlessexample.ingress.tls }}
  - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{ end }}
    secretName: {{ .secretName }}
  {{ end }}
{{- else }}
{{ toYaml .Values.headlessexample.ingress.tls | indent 4 }}
  {{ end }}
{{ end }}
  rules:
  {{- range .Values.headlessexample.ingress.hosts }}
    {{- if $ingressPath }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $ingressPath }}
        pathType: {{ $pathtype }}
        backend:
          service:
            name: {{ $fullName }}
            port: 
              number: {{ $svcPort }}
  {{- else }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ $pathtype }}
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  {{ end }}
 {{ end }}
{{ end }}
{{ end }}
