/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefaultContextSchema {
  entity: {
    [k: string]: unknown;
  };
  documents: {
    id?: string;
    category: string;
    type: string;
    issuer: {
      type?: string;
      name?: string;
      country: string;
      city?: string;
      additionalInfo?: {
        [k: string]: unknown;
      };
    };
    issuingVersion?: number;
    decision?: {
      status?: 'new' | 'pending' | 'revision' | 'approved' | 'rejected';
      rejectionReason?:
        | string
        | (
            | 'Suspicious document'
            | 'Document does not match customer profile'
            | 'Potential identity theft'
            | 'Fake or altered document'
            | 'Document on watchlist or blacklist'
          );
      revisionReason?:
        | string
        | (
            | 'Blurry image'
            | 'Missing page'
            | 'Invalid document'
            | 'Expired document'
            | 'Unreadable document'
          );
    };
    version?: number;
    pages: {
      ballerineFileId?: string;
      provider: 'gcs' | 'http' | 'stream' | 'file-system' | 'ftp' | 'aws_s3';
      uri: string;
      /**
       * Whether an effect is positive or negative
       */
      type: 'pdf' | 'png' | 'jpg';
      data?: string;
      metadata?: {
        side?: string;
        pageNumber?: string;
      };
    }[];
    properties: {
      email?: string;
      expiryDate?: string;
      idNumber?: string;
      [k: string]: unknown;
    };
  }[];
  [k: string]: unknown;
}
