export type UnifiedCallbackNames =
  | 'ubo-unified-api'
  | 'kyc-unified-api'
  | 'kyb-unified-api'
  | 'kyc-unified-api-decision'
  | 'aml-unified-api'
  | 'merchant-audit-report'
  | 'website-monitoring'
  | 'document-verification-unified-api'
  | 'facial-verification-unified-api'
  | 'business-document-verification-unified-api'
  | 'market-card-verification-unified-api'
  | 'address-verification-unified-api'
  | 'business-photo-analysis-unified-api'
  | 'loan-financial-analysis-unified-api';
