name: Test
description: Test the project

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Test
      shell: bash
      run: pnpm test -- --verbose false
      env:
        LOG_LEVEL: error
        JEST_HTML_REPORTER_INCLUDE_SUITE_FAILURE: "true"
        JEST_HTML_REPORTER_LOGO: "https://blrn-cdn-prod.s3.eu-central-1.amazonaws.com/images/ballerine_logo.svg"
        JEST_HTML_REPORTER_STATUS_FILTER: "failed"

    - name: Store test result
      if: failure()
      uses: actions/upload-artifact@v4.3.3
      id: artifact-upload-step
      with:
        name: test-report.html
        path: services/workflows-service/
        retention-days: 7

