---

- name: Replace VITE URL for backoffice
  lineinfile:
    path: '~/ballerine/apps/backoffice-v2/.env.example'
    regexp: '^(.*)VITE_API_URL(.*)$'
    line: "VITE_API_URL=https://{{ vite_api_url }}/api/v1/internal"
    backrefs: yes
  when: vite_api_url != ""

- name: Replace VITE URL for kyb-app
  lineinfile:
    path: '~/ballerine/apps/kyb-app/.env.example'
    regexp: '^(.*)VITE_API_URL(.*)$'
    line: "VITE_API_URL=https://{{ vite_api_url }}/api/v1/"
    backrefs: yes
  when: vite_api_url != ""

- name: Replace VITE URL for workflow-dashboard
  lineinfile:
    path: '~/ballerine/apps/workflows-dashboard/.env.example'
    regexp: '^(.*)VITE_API_URL(.*)$'
    line: "VITE_API_URL=https://{{ vite_api_url }}/api/v1/"
    backrefs: yes
  when: vite_api_url != ""

- name: Create Caddy directory for https
  ansible.builtin.file:
    path: "{{ install_dir }}/deploy/caddy"
    state: directory
  when: vite_api_url != ""

- name: create Caddyfile for https
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: "{{ install_dir }}/deploy/caddy/Caddyfile"
  when: vite_api_url != ""