/** @type { import("@cspell/cspell-types").CSpellUserSettings } */
module.exports = {
  version: '0.2',
  id: 'cspell-project-config',
  name: 'cspell Project Config',
  language: 'en',
  ignoreRegExpList: [
    'c[0-9a-z]{24}',
    '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}',
    '[a-zA-Z0-9+/]{2,}={0,2}',
  ],
  words: [
    'géné',
    'Lilyan',
    'Brockside',
    'buhgdawe',
    'clhz',
    'lhxy',
    'lhzd',
    'ajduq',
    'UBOs',
    'Ballerine',
    "Ballerine's",
    'ballerine',
    'blrn',
    'xstate',
    'Typecheck',
    'typecheck',
    'Astro',
    'astro',
    'astrojs',
    'shiki',
    'docsearch',
    'Cheatsheet',
    'frontmatter',
    'Encabezado',
    'sección',
    'Introducción',
    'Aglolia',
    'tsconfigs',
    'BACKOFFICE',
    'Backoffice',
    'backoffice',
    'commitlint',
    'VITE',
    'MXTSHOTA',
    'vite',
    'formkit',
    'hookform',
    'lukemorales',
    'tanstack',
    'clsx',
    'tailwindcss',
    'languagedetector',
    'lucide',
    'daisyui',
    'viewports',
    'msedge',
    'felte',
    'fontsource',
    'nestjs',
    'websockets',
    'Kamil',
    'Myśliwiec',
    'nestframework',
    'fintech',
    'jslib',
    'zerodevx',
    'compressorjs',
    'deepmerge',
    'mjpeg',
    'Prefs',
    'gstreamer',
    'sessionstore',
    'firstrun',
    'embeddable',
    'gzipped',
    'jsfiddle',
    'ekyc',
    'ICSS',
    'jmespath',
    'sibedge',
    'healthcheck',
    'isready',
    'intg',
    'accesscontrol',
    'testcontainers',
  ],
  maxNumberOfProblems: 1000,
  ignorePaths: [
    '*.snap',
    'node_modules',
    'package-lock.json',
    'coverage/**',
    'dist/**',
    'dist.*/**',
    'temp/**',
    'CHANGELOG.md',
    'package.json',
    '.cspell.json',
    'cspell.json',
    '.vscode/**',
    'tsconfig.tsbuildinfo',
    'stats.html',
    'currency-codes.ts',
    'states.ts',
    'countries.ts',
  ],
  flagWords: [],
  dictionaries: ['workspace'],
  ignoreWords: [],
};
