/** @type { import("@cspell/cspell-types").CSpellUserSettings } */
module.exports = {
  version: '0.2',
  id: 'cspell-project-config',
  name: 'cspell Project Config',
  language: 'en',
  words: [
    'Ballerine',
    "Ballerine's",
    'ballerine',
    'blrn',
    'xstate',
    'Typecheck',
    'typecheck',
    'Astro',
    'astro',
    'astrojs',
    'shiki',
    'docsearch',
    'Cheatsheet',
    'frontmatter',
    'Encabezado',
    'sección',
    'Introducción',
    'Aglolia',
    'tsconfigs',
    'BACKOFFICE',
    'Backoffice',
    'backoffice',
    'commitlint',
    'VITE',
    'MXTSHOTA',
    'vite',
    'formkit',
    'hookform',
    'lukemorales',
    'tanstack',
    'clsx',
    'tailwindcss',
    'languagedetector',
    'lucide',
    'daisyui',
    'viewports',
    'msedge',
    'felte',
    'fontsource',
    'nestjs',
    'websockets',
    'Kamil',
    'Myśliwiec',
    'nestframework',
    'fintech',
    'jslib',
    'zerodevx',
    'compressorjs',
    'deepmerge',
    'mjpeg',
    'Prefs',
    'gstreamer',
    'sessionstore',
    'firstrun',
    'embeddable',
    'gzipped',
    'jsfiddle',
    'ekyc',
    'ICSS',
    'jmespath',
    'sibedge',
    'healthcheck',
    'isready',
    'intg',
    'accesscontrol',
    'testcontainers',
  ],
  maxNumberOfProblems: 1000,
  ignorePaths: [
    '*.snap',
    'node_modules',
    'package-lock.json',
    'coverage/**',
    'dist/**',
    'dist.*/**',
    'temp/**',
    'CHANGELOG.md',
    'package.json',
    '.cspell.json',
    'cspell.json',
    '.vscode/**',
    'tsconfig.tsbuildinfo',
    'stats.html',
  ],
  flagWords: [],
  dictionaries: ['workspace'],
  ignoreWords: [],
};
