{{- if and .Values.workflowService.dbMigrate.enabled (not .Values.workflowService.migration) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.workflowService.nameOverride }}-db-data-migrations
  labels:
    app: {{ .Values.workflowService.nameOverride }}-db-data-migrations
  annotations:
    argocd.argoproj.io/hook: PostSync
    helm.sh/hook: post-install,post-upgrade
    argocd.argoproj.io/sync-wave: "100"
    helm.sh/hook-weight: "100"
    # helm.sh/hook-delete-policy: post-delete
spec:
  template:
    spec:
      {{- if .Values.workflowService.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.workflowService.image.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ .Values.workflowService.nameOverride }}
      restartPolicy: Never
      initContainers:
        - name: wait-for-migration
          image: pegasystems/k8s-wait-for:latest
          imagePullPolicy: IfNotPresent
          args: 
          - "pod"
          - "-lapp={{ .Values.workflowService.nameOverride }}"
      containers:
      - name: {{ .Values.workflowService.nameOverride }}-db-data-migrations
        securityContext:
          {{- toYaml .Values.workflowService.securityContext | nindent 12 }}
        image: "{{ .Values.workflowService.dbMigrate.image.repository }}:{{ .Values.workflowService.dbMigrate.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.workflowService.image.pullPolicy }}
        command: {{ .Values.workflowService.dbMigrate.image.command | toYaml | nindent 12 }}
        args: {{ .Values.workflowService.image.args | toYaml | nindent 12 }}
        {{- with .Values.workflowService.image.env }}
        env:
        {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.workflowService.dbMigrate.envFrom }}
        envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
  backoffLimit: {{ .Values.workflowService.backoffLimit }}
{{- end }}