export const workflowRuntimeDataContext = {
  entity: {
    data: {
      additionalInfo: {
        open_corporates: {},
        mainContact: {
          firstName: 'mockValue',
          lastName: 'mockValue',
          email: 'mockValue',
          phone: 'mockValue',
        },
        bank: {
          holderName: 'mockValue',
          holderFullAddress: 'mockValue',
          accountNumber: 'mockValue',
          iban: 'mockValue',
          swiftCode: 'mockValue',
          bankName: 'mockValue',
          bankAddress: 'mockValue',
          subBranch: 'mockValue',
          currency: 'mockValue',
        },
        store: {
          websiteUrls: 'mockValue',
          dba: 'mockValue',
          industry: 'mockValue',
          products: 'mockValue',
          established: 'mockValue',
          hasMobileApp: true,
          mobileAppName: 'mockValue',
          hasActiveWebsite: true,
          website: {
            operationEntitiesName: 'mockValue',
            contactDetails: 'mockValue',
            returnPolicyUrl: 'mockValue',
            shippingPolicyUrl: 'mockValue',
            aboutUsUrl: 'mockValue',
            productQuantityUrl: 'mockValue',
            productDescription: 'mockValue',
            productPrice: 'mockValue',
            websiteLanguage: 'mockValue',
          },
          processingDetails: {
            monthlySalesVolume: 5000,
            monthlyTransactions: 200,
            estimatedMonthlySalesClipsPay: 3000,
            estimatedMonthlyTransactionsClipsPay: 150,
            averageTicketSales: 25,
            maximumTicketSales: 200,
            isSpikeInSales: true,
            spikeSalesVolume: 150000,
            spikeTransactionNumber: 200,
            spikeOfVolumeInRegion: 30,
            mainContact: 'B2C',
          },
        },
        mainRepresentative: {
          firstName: 'mockValue',
          lastName: 'mockValue',
          additionalInfo: {
            jobTitle: 'mockValue',
          },
          dateOfBirth: 'mockValue',
          phone: 'mockValue',
        },
        ubos: [
          {
            firstName: 'mockValue',
            lastName: 'mockValue',
            nationality: 'mockValue',
            identityNumber: 'mockValue',
            email: 'mockValue',
            fullAddress: 'mockValue',
            percentageOfOwnership: 'mockValue',
          },
          {
            firstName: 'mockValue',
            lastName: 'mockValue',
            nationality: 'mockValue',
            identityNumber: 'mockValue',
            email: 'mockValue',
            fullAddress: 'mockValue',
            percentageOfOwnership: 'mockValue',
          },
        ],
        directors: [
          {
            firstName: 'mockValue',
            lastName: 'mockValue',
            nationality: 'mockValue',
            identityNumber: 'mockValue',
            email: 'mockValue',
            fullAddress: 'mockValue',
          },
          {
            firstName: 'mockValue',
            lastName: 'mockValue',
            nationality: 'mockValue',
            identityNumber: 'mockValue',
            email: 'mockValue',
            fullAddress: 'mockValue',
          },
        ],
        headquarters: {
          street: 'mockValue',
          streetNumber: 'mockValue',
          city: 'mockValue',
          country: 'mockValue',
          isDifferentFromPhysical: 'mockValue',
          physical: {
            street: 'mockValue',
            streetNumber: 'mockValue',
            city: 'mockValue',
            country: 'mockValue',
          },
        },
        registeredCapitalInYuan: 'mockValue',
      },
      registrationNumber: 'mockValue',
      country: 'mockValue',
      companyName: 'mockValue',
      taxIdentificationNumber: 'mockValue',
      numberOfEmployees: 'mockValue',
      businessType: 'mockValue',
    },
  },
};
