export const workflowRuntimeDataContext = {
  entity: {
    data: {
      country: 'GB',
      companyName: 'GOCARDLESS LTD',
      businessType: 'Sole Proprietorship',
      additionalInfo: {
        bank: {
          iban: '615216216012241',
          bankName: 'fkjfnaBank',
          currency: 'AMD',
          subBranch: '15151',
          swiftCode: 'qwrqttqt',
          holderName: '151612431rwq',
          bankAddress: 't0, dwahgsea, dwaiu15',
          accountNumber: '151423156151',
          holderFullAddress: 'tqtqtwq151516qwtwqtqt',
        },
        ubos: [
          {
            email: 'dwadw@dwawda.com',
            lastName: 'ddadwa',
            firstName: 'dwadwadaw',
            fullAddress: 'fwatatwa',
            nationality: 'dwaawddwa',
            identityNumber: 'dwadawadw',
            percentageOfOwnership: 25,
          },
          {
            email: 'dwadt1W@wada.com',
            lastName: 'PUPU',
            firstName: 'KAKI',
            fullAddress: 'twaadwada',
            nationality: 'dwaadwa',
            identityNumber: 'qw151121ewq',
            percentageOfOwnership: 51,
          },
        ],
        store: {
          dba: 'tqrwqr',
          website: {
            aboutUsUrl: 'https://google.com',
            mainWebsite: 'https://google.com',
            productPrice: 100,
            contactDetails: 'gawat, dwa Next',
            productQuantity: 512,
            returnPolicyUrl: 'https://google.com',
            websiteLanguage: 'Engliaaa',
            shippingPolicyUrl: 'https://google.com',
            productDescription: 'https://google.com',
          },
          industry: 'Education',
          products: '514521q',
          established: '1990-04-18T21:00:00.000Z',
          websiteUrls: 'https://google.com',
          hasMobileApp: true,
          mobileAppName: 'Bla App',
          hasActiveWebsite: true,
          processingDetails: {
            isSpikeInSales: 51321231,
            averageTicketSales: 215151,
            maximumTicketSales: 32151521412,
            monthlySalesVolume: 51421,
            monthlyTransactions: 514125,
            estimatedMonthlySalesClipsPay: 513215,
            estimatedMonthlyTransactionsClipsPay: 413215,
          },
        },
        directors: [
          {
            email: 'dwadaw@dwadwa.com',
            lastName: 'dwagafwa',
            firstName: 'dwadwadwa',
            fullAddress: 'wqrqq',
            nationality: 'Algerian',
            identityNumber: 1415214,
          },
        ],
        endUserId: 'clnd79taz0000y8uc1scxgqxo',
        mainContact: {
          email: 'dnioi@dwag.com',
          phone: '1513416121',
          lastName: 'BBlokh',
          firstName: 'Daniel',
        },
        headquarters: {
          city: 'London',
          street: 'Downing',
          country: 'GB',
          streetNumber: 199,
          isDifferentFromPhysical: false,
        },
        openCorporate: {
          vat: '',
          name: 'GOCARDLESS LTD',
          companyType: 'Private Limited Company',
          companyNumber: '07495895',
          jurisdictionCode: 'gb',
          incorporationDate: '2011-01-17',
        },
        mainRepresentative: {
          phone: '15132151512',
          lastName: 'Blokh',
          firstName: 'Daniel',
          dateOfBirth: '1990-12-13T22:00:00.000Z',
          additionalInfo: { jobTitle: 'CEO - Better than Alon' },
        },
        registeredCapitalInYuan: 512314351,
      },
      numberOfEmployees: 12,
      registrationNumber: '07495895',
      taxIdentificationNumber: '4135121351',
    },
    type: 'business',
    ballerineEntityId: 'clnd79taz0002y8uc4e8biscb',
  },
  flowConfig: { apiUrl: 'http://localhost:3000', tokenId: 'b70c9787-d3f2-4b6a-a379-aab0b34aff4f' },
  workflowRuntimeId: 'clnd79tc70007y8ucmulkkmcd',
};
