name: New Deploy workflows-service image

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Choose Environment'
        required: true
        default: 'dev'
        options:
          - 'sb'
          - 'prod'
  push:
    paths:
      # Run this pipeline only if there are changes in specified path
      - 'services/workflows-service/**'
    branches:
    - "cicd-auto-run-promote-with-sync-secrets"
    - "sb"
    - "prod"
        
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment'
        required: true
        default: 'dev'
      sha:
        type: string
        description: 'SHA ID'
        required: true


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/workflows-service
  SHORT_HASH: ${{ (github.event.name == 'workflow_call' && inputs.environment == 'dev' && inputs.sha) || (github.event.name != 'push' && inputs.environment == 'prod' && vars.SB_WF_SHORT_SHA || vars.DEV_WF_SHORT_SHA) || (github.event.name == 'push' && ((github.ref_name == 'prod' && vars.SB_WF_SHORT_SHA) || vars.DEV_WF_SHORT_SHA)) }}
  ENVIRONMENT: ${{ (github.event.name != 'push' && inputs.environment) || (github.event.name == 'push' && github.ref_name == 'prod' && 'prod' || github.event.name == 'push' && github.ref_name == 'sb' && 'sb' || github.event.name == 'push' && 'dev') }}

jobs:
  set_short_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Verify SHORT_HASH
        run: |
          echo "SHORT_HASH is ${{ env.SHORT_HASH }}"
          echo "SHORT_HASH is ${{ env.SHORT_HASH }}"
          echo "SHORT_HASH is $SHORT_HASH"

  tag-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          echo "sha_short=${{ env.SHORT_HASH }}" >> $GITHUB_OUTPUT
          if [ "${{ env.ENVIRONMENT }}" == "prod" ]; then
          echo "PROD_WF_SHORT_SHA=${{ env.SHORT_HASH }}" >> $GITHUB_ENV
          else
          echo "SB_WF_SHORT_SHA=${{ env.SHORT_HASH }}" >> $GITHUB_ENV
          fi

      - name: Update Service version in Environment
        if: ${{ env.ENVIRONMENT != 'dev' }}
        run: |
          if [ "${{ env.ENVIRONMENT }}" == "prod" ]; then
            ENV="PROD"
          elif [ "${{ env.ENVIRONMENT }}" == "sb" ]; then
            ENV="SB"
          else
            ENV="DEV"
          fi
          echo "$ENV"
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_CI_ENV_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/ballerine-io/ballerine/actions/variables/${ENV^^}_WF_SHORT_SHA" \
            -d "{\"name\":\"${ENV}_WF_SHORT_SHA\",\"value\":\"${{ env.SHORT_HASH }}\"}"

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
            ${{ runner.os }}-docker-
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Log in to the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Tag Existing Image
        if: ${{ env.ENVIRONMENT != 'dev' }}
        run: |
          if [ "${{ env.ENVIRONMENT }}" == "prod" ]; then
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-sb
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-sb ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-${{ env.ENVIRONMENT }}
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-sb ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.ENVIRONMENT }}
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-sb ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
          else
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-dev
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-dev ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-${{ env.ENVIRONMENT }}
            docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-dev ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.ENVIRONMENT }}
          fi
          docker images
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.SHORT_HASH }}-${{ env.ENVIRONMENT }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.ENVIRONMENT }}

  build-and-push-ee-image:
    runs-on: ubuntu-latest
    needs: [tag-and-push-image]
    outputs:
      SUBMODULE_SHORT_HASH: ${{ steps.lastcommit.outputs.shorthash }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Checkout wf-data-migration
        uses: actions/checkout@v4
        with:
          repository: ballerine-io/wf-data-migration
          token: ${{ secrets.SUBMODULES_TOKEN }}
          ref: ${{ env.ENVIRONMENT }}
          fetch-depth: 1
          path: services/workflows-service/prisma/data-migrations

      - name: Get Latest Commit ID
        id: lastcommit
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.SUBMODULES_TOKEN }}
          repo: wf-data-migration
          branch: ${{ env.ENVIRONMENT }}

      - name: Set Commit Id as Env 
        run: echo "SUBMODULE_SHORT_HASH=${{ steps.lastcommit.outputs.shorthash }}" >> $GITHUB_ENV
      
      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
            ${{ runner.os }}-docker-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Log in to the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ee Docker images
        id: eemeta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-ee
          tags: |
            type=raw,value=${{ env.ENVIRONMENT }}
            type=raw,value=${{ env.SHORT_HASH }}-${{ steps.lastcommit.outputs.shorthash }}-${{ env.ENVIRONMENT }}
            type=raw,value=latest,enable=${{ env.ENVIRONMENT == 'prod' }}
            type=sha,format=short
            
      - name: Build and push ee Docker image
        uses: docker/build-push-action@v5
        with:
          context: services/workflows-service
          file: services/workflows-service/Dockerfile.ee
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          tags: ${{ steps.eemeta.outputs.tags }}
          build-args: |
            "BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/workflows-service:${{ env.SHORT_HASH }}-${{ env.ENVIRONMENT }}"
  
  update-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push-ee-image
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout cloud-infra-config repository
        uses: actions/checkout@v4
        with:
          repository: ballerine-io/cloud-infra-config
          token: ${{ secrets.GIT_TOKEN }}
          ref: main
          fetch-depth: 1
          sparse-checkout: |
            kubernetes/helm/wf-service
          sparse-checkout-cone-mode: true
      - name: Check if values yaml file exists 
        id: update_helm_check
        shell: bash
        run: |
          if [ -f "kubernetes/helm/wf-service/${{ env.ENVIRONMENT }}-custom-values.yaml" ]; then
            echo "file_name=${{ env.ENVIRONMENT }}-custom-values.yaml" >> "$GITHUB_OUTPUT"
            echo ${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}
          else
            echo "file_name=dev-custom-values.yaml" >> "$GITHUB_OUTPUT"
            echo ${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}
          fi
            
      - name: Update workflow-service image version in the HelmChart
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ballerine-io/cloud-infra-config
          branch: main
          commitChange: true
          message: "Update ${{ env.ENVIRONMENT }} wf-service image Version to ${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}-${{ env.ENVIRONMENT }} - (Commit hash: ${{ github.sha }}, commit message: ${{ github.event.head_commit.message }})"
          token: ${{ secrets.GIT_TOKEN }}
          changes: |
            {
              "kubernetes/helm/wf-service/${{steps.update_helm_check.outputs.file_name}}": {
                "image.tag": "${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}-${{ env.ENVIRONMENT }}",
                "prismaMigrate.image.tag": "${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}-${{ env.ENVIRONMENT }}",
                "dbMigrate.image.tag": "${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}-${{ env.ENVIRONMENT }}",
                "dataSync.image.tag": "${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}-${{ env.ENVIRONMENT }}"
              }
            }
  
  sync-eks-secrets:
    runs-on: ubuntu-latest
    needs: [update-helm-chart]
    environment: ${{ github.env.ENVIRONMENT }}
    permissions:
      contents: read
    steps:
      - name: Configure Twingate
        uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.TWINGATE_SERVICE_KEY_SECRET_NAME }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
  
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: RoleSession

      - name: Update Kubeconfig for EKS Cluster
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: "Annotate new secrets in the operator"
        id: annotate_secrets
        shell: bash
        env:
          NAMESPACE: 'default'
        run: |
          echo "Annotating workflow secrets in  namespace: $NAMESPACE"
          kubectl annotate es wf-${{ env.ENVIRONMENT }}-external-secret -n "$NAMESPACE" force-sync=$(date +%s) --overwrite
          echo "All deployments in namespace '$NAMESPACE' have been restarted."

  send-to-slack:
    runs-on: ubuntu-latest
    needs: [update-helm-chart,build-and-push-ee-image]
    if: ${{ needs.update-helm-chart.result == 'success' }}
    environment: ${{ github.env.ENVIRONMENT }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Send alert to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: '${{ secrets.ARGO_SLACK_CHANNEL_ID }}'
          slack-message: "Test Wf-service Deployment in ${{ env.ENVIRONMENT }} with tag ${{ env.SHORT_HASH }}-${{ needs.build-and-push-ee-image.outputs.SUBMODULE_SHORT_HASH }}-${{ env.ENVIRONMENT }} build result: ${{ job.status }}. successfully updated the wf-service helm values for ${{ env.ENVIRONMENT }}."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.ARGO_SLACK_BOT_TOKEN }}

